### ISSUE TITLE
user_role is not working

### ISSUE THREAD

**Issue by takestar15** [joshfrench/rakismet#38]
I tried to send user_role parameter to Askimet, but it actually sends 'comment_user_role'.

rakismet_attrs :author => proc { user.full_name },
               :author_email => proc { user.email },
               :content => :body,
               :user_ip => proc { user.current_sign_in_ip },
               :user_role => 'administrator',
               :comment_type => 'blog-post'

Even I set user_role as 'administrator', it returns true. This is because of https://github.com/joshfrench/rakismet/blob/master/lib/rakismet/model.rb#L17, which converts 'user_role' to 'comment_user_role'.

**Comment by joshfrench** [comment]
`user_role` doesn't appear to be something that Akismet cares about: http://akismet.com/development/api/#comment-check

**Comment by takestar15** [comment]
I referred this blog.
http://blog.akismet.com/2012/07/20/pro-tip-testing-testing/

To simulate a negative (not spam) result, make a comment-check API call with the user_role set to administrator, and all other required fields populated with typical values.

**Comment by joshfrench** [comment]
Good catch! I should have time to put a patch together in the next few days. (Pull requests welcome, as well!)

**Comment by joshfrench** [comment]
I just pushed v1.5.1 to rubygems.org. Thanks for the patch!

**Comment by takestar15** [comment]
Thanks.
