### ISSUE TITLE
List required fields?

### ISSUE THREAD

**Issue by pyro2927** [joshfrench/rakismet#40]
Is it possible to list the required values in the `README`?  I'm not a regular Akismet user, so it took a little bit of work and looking and the `akismet_response`s to figure out what fields were needed.  As far as I can tell, the following values need to be populated:

* `author`
* `author_email`
* `content`
* `user_ip`
* `user_agent`

Just thinking of how to make the gem more approachable from a novice's standpoint.

**Comment by joshfrench** [comment]
The [Akismet API](http://akismet.com/development/api) should be the documentation of reference, I'd rather not reproduce it here and then be responsible for keeping in step.
