### ISSUE TITLE
permalink parameter is sent as comment_permalink

### ISSUE THREAD

**Issue by cfinke** [joshfrench/rakismet#46]
I don't know Ruby all that well, but it appears that the `permalink` parameter is actually being sent as `comment_permalink`, based on its inclusion in arrays like the one at https://github.com/joshfrench/rakismet/blob/c19ded8f10704f0924f37b1cd48cadd58ba569fe/spec/models/rakismet_model_spec.rb#L11

```
it "should have default mappings" do
    [:comment_type, :author, :author_email, :author_url, :content, :permalink].each do |field|
      fieldname = field.to_s =~ %r(^comment_) ? field : "comment_#{field}".intern
      AkismetModel.akismet_attrs[fieldname].should eql(field)
     end
    AkismetModel::akismet_attrs[:user_role].should eql(:user_role)
end
```

Can you confirm whether this is the case, and if so, just send the value in the `permalink` argument?

**Comment by joshfrench** [comment]
Hey, good catch! I just pushed v1.5.4 which should fix this.

**Comment by yukster** [comment]
Thanks for the quick turnaround!
